// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagementSystemAPI.Data;

#nullable disable

namespace SchoolManagementSystemAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClassTeacher", b =>
                {
                    b.Property<int>("Class_id")
                        .HasColumnType("int");

                    b.Property<int>("TeachersT_id")
                        .HasColumnType("int");

                    b.HasKey("Class_id", "TeachersT_id");

                    b.HasIndex("TeachersT_id");

                    b.ToTable("ClassTeacher");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfirmPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("School_Management_System.Models.Class", b =>
                {
                    b.Property<int>("Class_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Class_id"));

                    b.Property<int>("Class_number")
                        .HasColumnType("int");

                    b.HasKey("Class_id");

                    b.ToTable("Classs");
                });

            modelBuilder.Entity("School_Management_System.Models.Grade", b =>
                {
                    b.Property<int>("Grd_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Grd_id"));

                    b.Property<string>("Grd_Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Grd_id");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("School_Management_System.Models.Student", b =>
                {
                    b.Property<int>("Std_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Std_id"));

                    b.Property<int?>("Class_id")
                        .HasColumnType("int");

                    b.Property<int?>("GradeGrd_id")
                        .HasColumnType("int");

                    b.Property<int>("Std_Age")
                        .HasColumnType("int");

                    b.Property<string>("Std_Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Std_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubjectSbj_id")
                        .HasColumnType("int");

                    b.Property<int?>("TermTrm_id")
                        .HasColumnType("int");

                    b.HasKey("Std_id");

                    b.HasIndex("Class_id");

                    b.HasIndex("GradeGrd_id");

                    b.HasIndex("SubjectSbj_id");

                    b.HasIndex("TermTrm_id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("School_Management_System.Models.Subject", b =>
                {
                    b.Property<int>("Sbj_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sbj_id"));

                    b.Property<string>("Sbj_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Sbj_id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("School_Management_System.Models.Teacher", b =>
                {
                    b.Property<int>("T_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("T_id"));

                    b.Property<DateOnly>("Date_of_joining")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<string>("Teacher_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("T_id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("School_Management_System.Models.Term", b =>
                {
                    b.Property<int>("Trm_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Trm_id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Trm_id");

                    b.ToTable("Terms");
                });

            modelBuilder.Entity("SubjectTeacher", b =>
                {
                    b.Property<int>("SubjectSbj_id")
                        .HasColumnType("int");

                    b.Property<int>("TeachersT_id")
                        .HasColumnType("int");

                    b.HasKey("SubjectSbj_id", "TeachersT_id");

                    b.HasIndex("TeachersT_id");

                    b.ToTable("SubjectTeacher");
                });

            modelBuilder.Entity("ClassTeacher", b =>
                {
                    b.HasOne("School_Management_System.Models.Class", null)
                        .WithMany()
                        .HasForeignKey("Class_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Management_System.Models.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeachersT_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("School_Management_System.Models.Student", b =>
                {
                    b.HasOne("School_Management_System.Models.Class", null)
                        .WithMany("Students")
                        .HasForeignKey("Class_id");

                    b.HasOne("School_Management_System.Models.Grade", null)
                        .WithMany("Students")
                        .HasForeignKey("GradeGrd_id");

                    b.HasOne("School_Management_System.Models.Subject", null)
                        .WithMany("Students")
                        .HasForeignKey("SubjectSbj_id");

                    b.HasOne("School_Management_System.Models.Term", null)
                        .WithMany("Students")
                        .HasForeignKey("TermTrm_id");
                });

            modelBuilder.Entity("SubjectTeacher", b =>
                {
                    b.HasOne("School_Management_System.Models.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectSbj_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Management_System.Models.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeachersT_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("School_Management_System.Models.Class", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("School_Management_System.Models.Grade", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("School_Management_System.Models.Subject", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("School_Management_System.Models.Term", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
